[package]
name = "mft_rust_sim"
version = "0.1.0"
edition = "2021"

[lib]
name = "mft_rust_sim"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.3", features = ["extension-module"] }
rand = "0.8.5"
rand_distr = "0.4.3"

